# Generated by Django 4.2.1 on 2023-05-29 04:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('scout_app', '0002_alter_search_latitude_alter_search_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='search',
            name='date_searched',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='search',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
